version: '1'
services:
  wts_api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: 3000
      ADMIN_PASS: 12345689
      NODE_ENV: development
  mongo_db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
